#language:es
Característica:BúsquedaexitosadeperfildeusuarioexistenteenGitHubyvisualizacióncompletademétricas,informaciónpersonalylistadeseguidores

ComoUsuariodelSistema
QuieroPoderBuscarUnPerfilDeUsuarioExistenteEnGitHub
ParaPoderVisualizarSusMétricas,InformaciónPersonalYListaDeSeguidoresDeFormaCompleta

Antecedentes:
DadoQueElUsuarioTieneAccesoAlSistemaYAInternet
YLaAPIDeGitHubEstáDisponibleYAccesible

Esquemadelescenario:BúsquedaExitosaDePerfilDeUsuarioExistenteEnGitHub
DadoQueElUsuarioAccedeAlComponenteDeBúsquedaDePerfilesGitHub
CuandoElSistemaCargueLaPágina
EntoncesElSistemaMuestraElInputDeTextoYElBotónConIconoDeLupaCorrectamente

CuandoElUsuarioIngresaElNombreDeUsuario"<username>"EnElCampoDeBúsqueda
EntoncesElNombreDeUsuarioSeIngresaCorrectamenteEnElCampoDeTexto

CuandoElUsuarioPresionaElBotónDeBúsqueda
EntoncesElSistemaRealizaLaConsultaALaAPIDeGitHub
YElSistemaMuestraUnIndicadorDeCargaMientrasProcesaLaSolicitud

CuandoLaConsultaSeCompletaExitosamente
EntoncesElSistemaVisualizaElDashboardDeMétricasEnLaParteSuperior
YElSistemaMuestraCorrectamenteLaCantidadDeRepositoriosPúblicos
YElSistemaMuestraCorrectamenteElNúmeroTotalDeSeguidores
YElSistemaMuestraCorrectamenteElNúmeroDePerfiflesQueSigue
YElSistemaMuestraCorrectamenteLaCantidadTotalDeGistsPúblicos

YElSistemaVerificaLaSecciónIzquierdaConInformaciónPersonalDelUsuario
YElSistemaMuestraCorrectamenteElAvatarDelUsuario
YElSistemaMuestraCorrectamenteElNombreCompletoYElUsername
YElSistemaMuestraCorrectamenteLaBiografía
YElSistemaMuestraCorrectamenteLaUbicaciónYLaEmpresa
YElSistemaMuestraCorrectamenteElEnlaceWeb
YElSistemaMuestraElBotónFollow

YElSistemaVerificaLaSecciónDerechaConLaListaDeSeguidores
YElSistemaPresentaUnaListaVerticalDeSeguidoresConAvatarNombreYEnlace

YElSistemaVerificaElIndicadorDeLímiteDeConsultasDeLaAPI
YElSistemaMuestraElIndicadorDeRequestsInformandoSobreElLímiteDeLaAPIConsumida

CuandoLaListaDeSeguidoresExcedeElTamañoDelContenedor
EntoncesLaListaPermiteElDesplazamientoVerticalParaVisualizarTodosLosSeguidores

CuandoElUsuarioHaceClicEnElEnlaceDeUnSeguidorDeLaLista
EntoncesElSistemaRedirigeCorrectamenteALaPáginaCorrespondienteDelPerfilDeGitHubDelSeguidorSeleccionado

Ejemplos:
|username|
|octocat|
|torvalds|
|mojombo|